### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by Ramko9999** [rohanshiva/gitgame#111]
Backend:
- [x] **Exception Handling:** Will the system remain in a consistent state in the case of an exception?
- [x] **Logging:** Are exceptions captured and logged? Do the logs themselves provide enough signal to understand the state of the system?
- [x] **Rate Limiting:** Do fragile endpoints (`/misc/feedback`) have rate limits?
- [x] **Observability:** Are we capturing API metrics? Frontend metrics? Database metrics?
- [x] **Security:** Are non-public endpoints inaccessible to the public?
